version: "3"
volumes:
  db-data:
  db:
    image: postgres:12.6
    ports:
      - "5432:5432"
    labels:
      name: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=admin
